// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.
import { createApiLeaf } from "kitcn/server"
import type { inferApiInputs, inferApiOutputs } from "kitcn/server"

import { api as convexApi } from "../functions/_generated/api.js"

export const api = {
	things: {
		create: createApiLeaf<"mutation", typeof import("../functions/things").create>(
			convexApi["things"]["create"],
			{ auth: "required", type: "mutation" }
		),
		generateUploadUrl: createApiLeaf<
			"mutation",
			typeof import("../functions/things").generateUploadUrl
		>(convexApi["things"]["generateUploadUrl"], { auth: "required", type: "mutation" }),
		get: createApiLeaf<"query", typeof import("../functions/things").get>(
			convexApi["things"]["get"],
			{ auth: "required", type: "query" }
		),
		list: createApiLeaf<"query", typeof import("../functions/things").list>(
			convexApi["things"]["list"],
			{ auth: "required", type: "query" }
		),
		remove: createApiLeaf<"mutation", typeof import("../functions/things").remove>(
			convexApi["things"]["remove"],
			{ auth: "required", type: "mutation" }
		),
		update: createApiLeaf<"mutation", typeof import("../functions/things").update>(
			convexApi["things"]["update"],
			{ auth: "required", type: "mutation" }
		),
	},
	_http: {},
} as const

export type Api = typeof api
export type ApiInputs = inferApiInputs<Api>
export type ApiOutputs = inferApiOutputs<Api>
