// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.
import type { InferInsertModel, InferSelectModel } from "kitcn/orm"
import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server"
import type { inferApiInputs, inferApiOutputs } from "kitcn/server"

import type { tables } from "../functions/schema"

export const api = {
	things: {
		create: createApiLeaf<"mutation", typeof import("../functions/things").create>(
			createGeneratedFunctionReference<
				"mutation",
				"public",
				typeof import("../functions/things").create
			>("things:create"),
			{ auth: "required", type: "mutation" }
		),
		generateUploadUrl: createApiLeaf<
			"mutation",
			typeof import("../functions/things").generateUploadUrl
		>(
			createGeneratedFunctionReference<
				"mutation",
				"public",
				typeof import("../functions/things").generateUploadUrl
			>("things:generateUploadUrl"),
			{ auth: "required", type: "mutation" }
		),
		get: createApiLeaf<"query", typeof import("../functions/things").get>(
			createGeneratedFunctionReference<"query", "public", typeof import("../functions/things").get>(
				"things:get"
			),
			{ auth: "required", type: "query" }
		),
		list: createApiLeaf<"query", typeof import("../functions/things").list>(
			createGeneratedFunctionReference<
				"query",
				"public",
				typeof import("../functions/things").list
			>("things:list"),
			{ auth: "required", type: "query" }
		),
		remove: createApiLeaf<"mutation", typeof import("../functions/things").remove>(
			createGeneratedFunctionReference<
				"mutation",
				"public",
				typeof import("../functions/things").remove
			>("things:remove"),
			{ auth: "required", type: "mutation" }
		),
		update: createApiLeaf<"mutation", typeof import("../functions/things").update>(
			createGeneratedFunctionReference<
				"mutation",
				"public",
				typeof import("../functions/things").update
			>("things:update"),
			{ auth: "required", type: "mutation" }
		),
	},
	_http: {},
} as const

export type Api = typeof api
export type ApiInputs = inferApiInputs<Api>
export type ApiOutputs = inferApiOutputs<Api>

export type TableName = keyof typeof tables
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>
