// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

export const meta = {
  things: {
    create: { auth: 'required', type: 'mutation' },
    get: { auth: 'required', type: 'query' },
    list: { auth: 'required', type: 'query' },
    remove: { auth: 'required', type: 'mutation' },
  },
  _http: {},
} as const;

export type Meta = typeof meta;
